name: Generate release APK and AAB

on:
  workflow_dispatch:

jobs:
  apk:
    name: Generate release builds
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Generate keystore.properties
        run: |
          cat <<EOF > keystore.properties
          storePassword:${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword:${{ secrets.KEY_PASSWORD }}
          keyAlias:${{ secrets.ALIAS }}
          storeFile:./keystore.jks
          EOF

      - name: Decode keystore and create jks
        run: echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > ./app/keystore.jks

      - name: Build release APK
        run: bash ./gradlew assembleRelease --stacktrace

      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk

      - name: Build release AAB
        run: bash ./gradlew bundleRelease --stacktrace

      - name: Upload debug AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release.aab
          path: app/build/outputs/bundle/release/app-release.aab
